#!/usr/bin/env bash
set -e
HIE_OPTS="-fwrite-ide-info"
RTS_OPTS="-p"
CC_OPTS="-fprof-auto -rtsopts -O1 -with-rtsopts=$RTS_OPTS -fexternal-interpreter"
stack build stacker-fake-pkg --ghc-options="$HIE_OPTS $CC_OPTS -hiedir target/hie" --profile
stack exec stacker-fake-pkg --rts-options="$RTS_OPTS" --profile 2>&1 1>/dev/null
if [[ $# -gt 0 ]]; then
	stack build stacker --ghc-options="$HIE_OPTS $CC_OPTS -hiedir hie" --profile
	stack exec stacker --rts-options="$RTS_OPTS" --profile "$@"
fi